name: Test, Build & Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # --------------------
  # Tests
  # --------------------
  tests:
    name: Tests (Go + Rust)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true
          cache-dependency-path: go/go.sum
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
      - uses: Swatinem/rust-cache@v2

      - name: Run all tests
        run: make test-all

  # --------------------
  # Build
  # --------------------
  build:
    name: Build (Go + Rust)
    runs-on: ubuntu-latest
    needs: [ tests ]   # only build if tests pass

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true
          cache-dependency-path: go/go.sum
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
      - uses: Swatinem/rust-cache@v2

      - name: Build all binaries
        run: make all

  # --------------------
  # Rust clippy
  # --------------------
  clippy:
    name: Rust Clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: clippy  # For the 'clippy' job
      - uses: Swatinem/rust-cache@v2

      - name: Run clippy
        run: make clippy

  # --------------------
  # Go lint
  # --------------------
  golangci-lint:
    name: Go golangci-lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          go-version: stable
          cache: true
          cache-dependency-path: go/go.sum
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.6
          install-only: true

      - name: Run golangci-lint
        run: make golangci-lint
